### ISSUE TITLE
Androidmanifest.xml

### ISSUE THREAD

**Issue by kjsolo** [MasayukiSuda/EasingInterpolator#2]
Error:.../src/main/AndroidManifest.xml:30:9-36 Error:
    Attribute application@allowBackup value=(false) from AndroidManifest.xml:30:9-36
    is also present at [com.daasuu:EasingInterpolator:1.0.0] AndroidManifest.xml:12:9-35 value=(true).
    Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:28:5-276:19 to override.
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':presentation:processDebugManifest'.
  
  > Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:30:9-36
  > is also present at [com.daasuu:EasingInterpolator:1.0.0] AndroidManifest.xml:12:9-35 value=(true).
  > Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:28:5-276:19 to override.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by MasayukiSuda** [comment]
Please write your AndroidManifest  
 [ tools:replace="android:allowBackup" ]
<a href="http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Attributes-markers-examples">see details </a>
