### ISSUE TITLE
Use Interpolator in a xml file

### ISSUE THREAD

**Issue by Daksh14** [MasayukiSuda/EasingInterpolator#5]
This is supposed to be my animation in the xml
```
<?xml version="1.0" encoding="utf-8"?>
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
   android:interpolator="@android:anim/accelerate_interpolator"
   android:fromAlpha="0.0" android:toAlpha="1.0" android:duration="100" />
```
Now i can't do it programmatically as i'm animating this
`popupWindow.setAnimationStyle(R.style.popup_window_animation_phone);`
And the file has to be in the style resource.
So can you help me setting the Interpolator  for this animation in xml?

**Comment by MasayukiSuda** [comment]
use binding adapter
