### ISSUE TITLE
Service End for JCenter

### ISSUE THREAD

**Issue by hearsilent** [MasayukiSuda/EasingInterpolator#8]
https://developer.android.com/studio/build/jcenter-migration

**Comment by kojofosu** [comment]
Made a fork that migrates the library from jcenter to jitpack.  You can use my fork till maintainer merges pull request.
Link https://github.com/kojofosu/EasingInterpolator

**Comment by MasayukiSuda** [comment]
Thanks for reporting back.
I fixed it, please read the ReadME.
